name: sims
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib-base=3.1.3
  - numpy=1.18.1
  - pip=20.1.1
  - python=3.8.3
  - scipy=1.4.1
  - xlrd=1.2.0
  - pip:
    - appnope==0.1.0
    - backcall==0.2.0
    - bleach==3.1.5
    - cycler==0.10.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - ipykernel==5.3.0
    - ipython==7.15.0
    - ipython-genutils==0.2.0
    - matplotlib==3.2.1
    - nbformat==5.0.7
    - numpy==1.18.5
    - packaging==20.4
    - pandas==1.0.4
    - prometheus-client==0.8.0
    - ptyprocess==0.6.0
    - pyzmq==19.0.1
    - send2trash==1.5.0
    - tabulate==0.8.7
    - terminado==0.8.3
    - wcwidth==0.2.4
    - webencodings==0.5.1

